# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k7qbaUZVo617H6Y6kJdQX6awfXzrr3nS
"""

import streamlit as st
from google.cloud import bigquery
from google.oauth2 import service_account
import pandas as pd
import altair as alt

# ----------------------------
# PAGE SETUP
# ----------------------------
st.set_page_config(page_title="BigQuery Dashboard", layout="wide")
st.title("📊 BigQuery Live Dashboard")

# ----------------------------
# CONNECT TO BIGQUERY
# ----------------------------
# Load credentials from Streamlit Secrets
creds_dict = st.secrets["google_credentials"]
credentials = service_account.Credentials.from_service_account_info(creds_dict)
client = bigquery.Client(credentials=credentials)

# ----------------------------
# QUERY SECTION
# ----------------------------
st.sidebar.header("⚙️ Query Settings")

# Example Query
query = st.sidebar.text_area(
    "Enter your BigQuery SQL:",
    """SELECT category, COUNT(*) as total
    FROM `your_project.your_dataset.your_table`
    GROUP BY category
    ORDER BY total DESC
    LIMIT 10""",
    height=150
)

# Run the Query
if st.sidebar.button("Run Query"):
    st.info("Running query...")
    df = client.query(query).to_dataframe()
    st.success("✅ Query successful!")

    # ----------------------------
    # DISPLAY RESULTS
    # ----------------------------
    st.write("### 📋 Query Results")
    st.dataframe(df, use_container_width=True)

    # Chart
    if len(df.columns) >= 2:
        col_x, col_y = df.columns[:2]
        chart = (
            alt.Chart(df)
            .mark_bar()
            .encode(
                x=alt.X(col_x, sort='-y'),
                y=col_y,
                tooltip=list(df.columns)
            )
            .interactive()
        )
        st.write("### 📈 Visualization")
        st.altair_chart(chart, use_container_width=True)
    else:
        st.warning("⚠️ Need at least 2 columns to plot a chart.")
else:
    st.info("Enter a query and click 'Run Query' to view results.")